### ISSUE TITLE
Dependency "open" is flagged as critical severity vulnerability 

### ISSUE THREAD

**Issue by fitzk** [smollweide/node-mock-server#102]
This is a bug regarding a vulnerable dependency of this project called [open](https://www.npmjs.com/package/open).

[vulnerability report ](https://nodesecurity.io/advisories/663)

Someone posted a github issue in open's repo suggesting that this package [opener](https://www.npmjs.com/package/opener) is a good alternative.

**Comment by smollweide** [comment]
thanks @fitzk 
it's published here in [v0.23.2](https://github.com/smollweide/node-mock-server/releases/tag/0.23.2)
