### ISSUE TITLE
Serve Dist folder with node-mock-server

### ISSUE THREAD

**Issue by BuruY** [smollweide/node-mock-server#110]
Hi @smollweide , 

For test purposes I want to perform testing on a build with node-mock-server as a backend.
When I build the application with specific parameters it creates a dist folder with an index.html file.

In the AppController.js file I made two adjustments in order to be able to serve the dist folder and added following snippets:
```
if (this.options.serveDistFiles) {
    app.use(express.static(mockConfig.distPath));
} else {
    app.use('/src', express.static(__dirname + '/../../src'));
    app.use('/node_modules', express.static(__dirname + '/../../node_modules'));
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: true }));
    app.set('view engine', 'ejs');
    app.set('views', __dirname + '/../../views');
}
```
and
```
if (this.options.serveDistFiles) {
    app.all('/*', function (req, res, next) {
        // Just send the index.html for other files to support HTML5Mode
        if (req.originalUrl.indexOf('api/') == -1) {
            res.sendFile('index.html', { root: this.options.distPath  });
        } else {
            next();
        }
    });
}
```

This introduces two configurable options for the mockserver:
```
this.options.serveDistFiles
this.options.distPath 
```

This way I can use it the way I need it to work, I am not sure this is the correct way of solving my issue though. The only problem with this solution is that I need to fork this package and implement it in my project instead of using it as an NPM package. 

Is there any way we can implement this?

**Comment by BuruY** [comment]
If you wish I can create a pull request

**Comment by smollweide** [comment]
Hi @BuruY,
thank you for the issue.
I'm not sure what you mean with `build the application` but I assume your application's build and this build creates the dist directory, is that correct?

And your idea is to make everything inside of this dist directory available in a route on the `node-mock-server` instance, isn't it?

**Comment by smollweide** [comment]
If my assumptions are correct. I would recommend you to start a second node app with your client application.
Then you can start both the mock-server and your server in parallel.

**Comment by BuruY** [comment]
I Struggled for a while how to effectively do this on a build server.. A Package called Concurrently was the solution to run multiple nodes at the same time.
