### ISSUE TITLE
response status code is not respected

### ISSUE THREAD

**Issue by maiksensi** [smollweide/node-mock-server#113]
Hey, 

I just tried out node-mock-server and it seems that it does not respect different status codes for responses. 

say I have `desc.json`: 

```
{
  "desc": "delete something",
  "security": [],
  "protected": false,
  "status": "",
  "response": {
    "statusCode": 200,
    "schema": {
      "type": "application/json"
    }
  }
}
```
If I access the corresponding resource, I get a expected status code of `200` and in the UI the responses is shown correctly. 

Changing the status code (to `204` for example) in `desc.json` leads to the following behavior: 
- The UI shows the new status code as a response status code. 
- using curl to access the resource, a `200` is still returned. 

I guess I am missing something here. Any advice what I have to change or add so that the status code will be repsected? Please let me know if you need additional information.

**Comment by smollweide** [comment]
Hi @maiksensi,
it seems you need to change the expected response.
Therefor you should use the UI [expected-response](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-expected-response.md).

![kapture 2018-09-07 at 17 54 42](https://user-images.githubusercontent.com/2912007/45230018-d49b8c80-b2c7-11e8-85d6-18083bb3335c.gif)

If this solves your problem please close the ticket.

Best,
Simon

**Comment by maiksensi** [comment]
Hi @smollweide, 

thank you for your fast feedback. This does indeed solve my problem. Thank for the awesome project, helped me a lot so far! 

Best, 
Maik.
