### ISSUE TITLE
Importing Har Files as Mock Requests/Responses

### ISSUE THREAD

**Issue by logicquest** [smollweide/node-mock-server#114]
It is often difficult for developers to several hundreds of request-response combinations manually. On using this option, developers can easily import the existing apis to this service and kickstart to use Mock Server.

Screen 1: 
![image](https://user-images.githubusercontent.com/3636908/45116137-bb97ad80-b106-11e8-8231-c57bce94cb64.png)

Screen 2: 
![image](https://user-images.githubusercontent.com/3636908/45116152-c5b9ac00-b106-11e8-86a9-e1512a8659e0.png)

Screen 3:
![image](https://user-images.githubusercontent.com/3636908/45116166-cf431400-b106-11e8-9a29-094b6e67ff6c.png)

**Comment by raphapy** [comment]
Do we need to use an option to have this feature enabled?
