### ISSUE TITLE
How to filter json based on Query params?

### ISSUE THREAD

**Issue by bori87** [smollweide/node-mock-server#128]

**Comment by smollweide** [comment]
Hi @bori87,
you can take a look into this example:

https://github.com/smollweide/node-mock-server/blob/59edf4f1310b3d83970a44357e40567a4918a296/demo/rest/products/%23%7BproductCode%7D/GET/mock/request-data.json#L3

Additionally you can use logic in json responses by using ejs.

The second option is to use the middleware 
https://github.com/smollweide/node-mock-server/blob/master/doc/readme-middleware.md

Hope that helps you.
