### ISSUE TITLE
413 Error: request entity too large

### ISSUE THREAD

**Issue by andreacampaci** [smollweide/node-mock-server#133]
Hi,
When I try to do a POST with base64 image I got this error:
```
Request Method:	
POST	
Status Code:	
413 Payload Too Large	
Remote Address:	
127.0.0.1:8080
Referrer Policy:
no-referrer-when-downgrade
```
```
PayloadTooLargeError: request entity too large
```

Please, can you tell me how to increase the payload's limit?  

Thank you 

Andrea

**Comment by smollweide** [comment]
Hello Andrea,

replace of 
`app.use(bodyParser.json());`

with
`app.use(bodyParser.json({ limit: '50mb' }))`

In the AppController should solve the problem. Could you please test it with your configuration?

https://github.com/smollweide/node-mock-server/blob/master/lib/controller/AppController.js#L97

Greetings and thank you

**Comment by smollweide** [comment]
Hi @andreacampaci,
done with release 0.25.2
