### ISSUE TITLE
Tunnels with https target

### ISSUE THREAD

**Issue by sebastienfouache** [smollweide/node-mock-server#134]
Hello, i m tunnelling calls to real enpoints but https look to crash if certificats not valid or self signed.
```
✖ Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
```

Hint : 
https://stackoverflow.com/questions/46968937/nodejs-request-post-not-working-for-https-website/46968984#46968984

**Comment by sebastienfouache** [comment]
@smollweide any suggestion ?

**Comment by smollweide** [comment]
Hi Sebastien,
thanks. Feel free to add a PR

**Comment by smollweide** [comment]
Hi Sebastien,
that's not secure but you can add this in the mock server js file:

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```
