### ISSUE TITLE
node-mock-server doesn't parse 'application/json' content type

### ISSUE THREAD

**Issue by kabaybodia** [smollweide/node-mock-server#136]
node-mock-server doesn't parse 'application/json' content type request data
https://github.com/smollweide/node-mock-server/blob/a97d9231045a1e856df803cafb2e3b3cb6834a28/lib/controller/AppController.js#L97
As a solution might be replacement of:  app.use(bodyParser.json());
with: app.use(express.json());
since in the project express version 4.16+ is used (https://medium.com/@mmajdanski/express-body-parser-and-why-may-not-need-it-335803cd048c)

**Comment by smollweide** [comment]
Hi @kabaybodia;
done with release 0.25.2
