### ISSUE TITLE
How to handle xml response in mock-server

### ISSUE THREAD

**Issue by ParthCodeDev** [smollweide/node-mock-server#145]
I have a requirement to return xml data than it is  possible with mock server to read xml file and return the xml data ??

**Comment by smollweide** [comment]
Hi @ParthCodeDev,
yes it is by just adding a xml file.
Here an example: https://github.com/smollweide/node-mock-server/tree/master/demo/rest/products/%23%7BproductCode%7D%23static/GET/mock

**Comment by ParthCodeDev** [comment]
> Hi @ParthCodeDev,
> yes it is by just adding a xml file.
> Here an example: https://github.com/smollweide/node-mock-server/tree/master/demo/rest/products/%23%7BproductCode%7D%23static/GET/mock

Thank you so much @smollweide
