### ISSUE TITLE
It doesn’t copy  example responses from swagger 

### ISSUE THREAD

**Issue by swapnilUI** [smollweide/node-mock-server#146]
Its not an issue I guess might have not thought of. I was just wondering it would copy sample response from imported swagger to success.json or create files for all the responses provided in swagger file.

**Comment by swapnilUI** [comment]
Ok i got it. I did modify swaggerPathMethods.js also modified swaggerImport.js to import local files. Thanks 😊

**Comment by silasb** [comment]
I'm interested in your change.  Do you have a diff of your changes?
