### ISSUE TITLE
Switching between configured Responses

### ISSUE THREAD

**Issue by codibias** [smollweide/node-mock-server#148]
Hi, I found that switching between configured responses is possible by using the ui, which is great. I am trying to find out if this can also be done by rest api. E.g. by put request on a certain path. Is that possible or is there any other way to configure responses using the api endpoints?

**Comment by smollweide** [comment]
Hi @tobiasneubert,
yes there are multiple ways. 
- You can use [collections](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-collections.md).
- By using _expected [query or header](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-expected-response.md)
