### ISSUE TITLE
HTTP code does work with response header

### ISSUE THREAD

**Issue by ngoccuong291** [smollweide/node-mock-server#149]
When I tried to setup a mock response with custom HTTP code (i.e: 302) and a custom header (Location=https://www.google.com), the header did not get sent back along with the response and the http code did not come neither.
If I setup the same response header with the standard success.json (HTTP code 200) then it works fine.
After playing with different header, looks like the header "Location" was the problem, when I chose something else (i.e: my-custom-header), it worked fine

**Comment by smollweide** [comment]
Hi @ngoccuong291,
did you checked out the documentation here?
https://github.com/smollweide/node-mock-server/blob/master/doc/readme-response-header.md

There are two ways of defining headers.
- Globally as described in documentation
- Or for a specific response like here: https://github.com/smollweide/node-mock-server/blob/master/demo/rest/products/%23/GET/mock/success.headers.json
