### ISSUE TITLE
Can someone help me deploy this on Azure or google cloud? 

### ISSUE THREAD

**Issue by Ankita-0607** [smollweide/node-mock-server#152]
I have been trying to deploy this app on cloud server to give support to my frontend app. But I am not able to deploy this on azure or GCP even after multiple attempts. It gives 500 error and I am not able to debug the problem. ANy help would be appreciated.

**Comment by smollweide** [comment]
Hi @Ankita-0607,
my first question is why. This is a mock server and should not be deployed somewhere.
It's build for mocking rest api's.
