### ISSUE TITLE
Set headers into response

### ISSUE THREAD

**Issue by dfiori** [smollweide/node-mock-server#23]
Hi,
I'm doing some experiments with your library but I'm facing with not clear instructions.
For example: how can I set the headers in the GET/POST mock response?

I would suggest you to write a more detailed user guide or some example too, because there's a bit messy right now.

**Comment by smollweide** [comment]
Hi dfiori,
Thanks for your issue. It's currently not possible to set header's for each response but you can add/change the given headers in the [options](https://github.com/smollweide/node-mock-server#optionsaccesscontrolexposeheaders).

Todo's
- [ ] add options.headers for global headers (will be added for each response)
- [ ] define header for one response (second file ended with *.headers.json)

Your criticism about the instructions is a important point for me and I will take care on it for version 1.0.0.

**Comment by smollweide** [comment]
Implemented with [v0.10.0](https://github.com/smollweide/node-mock-server/releases/tag/0.10.0)

**Comment by leegee** [comment]
Can this be done via the GUI ?

**Comment by smollweide** [comment]
Not yet no. But I'm working on v1.0.0 and will add it there.

**Comment by leegee** [comment]
It's a lovely module, I hope to use it again! Thank you very much.
