### ISSUE TITLE
Demo - func-imported not found

### ISSUE THREAD

**Issue by ghost23** [smollweide/node-mock-server#27]
When I run the demo, I get this error:

✖ Folder "C:\Users\mail\IdeaProjects\testmocker\node-mock-server\demo\func-imported" not found!

I see here

https://github.com/smollweide/node-mock-server/blob/master/demo/index.js#L5

the folder is defined, but it does not exist in the demo folder.

**Comment by smollweide** [comment]
Hi Sven,
thanks for your bug report.
It's fixed with [0.12.1](https://github.com/smollweide/node-mock-server/releases/tag/0.12.1)
`npm i node-mock-server@0.12.1 --save-dev`
