### ISSUE TITLE
[Request] Ability to dynamically change status response code

### ISSUE THREAD

**Issue by crbanman** [smollweide/node-mock-server#29]
I'm doing some basic parameter validation on one of my mocks and would like to be able to return a different status code when a parameter is missing or incorrect. Currently, the only way this can be done is to create a separate error response and select it using the UI.

**Comment by crbanman** [comment]
Created a pull request with a potential solution. #30

**Comment by smollweide** [comment]
Hi @crbanman,
I created an middleware object which gives you the power to change the response.
- [documentation](https://github.com/smollweide/node-mock-server/blob/feature/middleware/doc/readme-middleware.md)
- [example](https://github.com/smollweide/node-mock-server/blob/feature/middleware/demo/index.js#L22)

The difference to your approach is that there is a new option in the ui to select "middleware" as response. 
Will this approach be okay for you?

**Comment by crbanman** [comment]
Hey @smollweide,
Your current solution does solve my problem.

It would be nice if each service could define their own middleware code inside the same directory as the other files for that service. But that's more of a "nice to have" feature as your current solution will work for me.

**Comment by smollweide** [comment]
Hi @crbanman,
it's released with in version 0.13.0

`npm i node-mock-server@0.13.0 --save-dev`

Thank you for your patience.
