### ISSUE TITLE
desc.json response status code not respected

### ISSUE THREAD

**Issue by pcaithness** [smollweide/node-mock-server#41]
I am creating a series of POST and PUT endpoints. When the mock server responds to these requests, I want to specify that they return the correct http status code:

If I specify that status code in the response object within desc.json, it is not being respected and always returns 200 (unless I use an error response with an error-401.json kind of response file).

"response": {
		"statusCode": 201,
		"schema": {
			"type": "application/json"
		}
	}

I am using v0.14.0

**Comment by smollweide** [comment]
Hi @pcaithness,
there are two way's to define the statusCode:
1. use the response file name. Like "error-401.json" or "success-201.json" and select the response by using the UI. [readme-expected-response](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-expected-response.md) 
2. or as a more dynamic solution you can use a middleware. [readme-middleware](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-middleware.md) [example](https://github.com/smollweide/node-mock-server/blob/master/demo/index.js#L27)

**Comment by pcaithness** [comment]
thanks @smollweide 
I did not know you could specify the status code on the success responses.
