### ISSUE TITLE
ReST responses that are not json

### ISSUE THREAD

**Issue by dschulten** [smollweide/node-mock-server#44]
I tried to create a success.html containing an html fragment instead of json and use the radiobutton to select it. The response was empty and the log showed that response.txt was set to success.html, but an error stating that success.json could not be found. 

Ideally, it should consider the Accept request header, so it would be possible to choose 'success' (not success. html), then request always the same resource and get success.json when Accept:application/json was requested, success.xml for application/xml, success.html for text/html etc. 

If you are ok with that approach, you can assign me :-)

**Comment by dschulten** [comment]
started implementation

**Comment by dschulten** [comment]
stopped implementation, waiting for the outcome of #42

**Comment by smollweide** [comment]
Sounds really magic for me. Maybe you should handle this special case by using the middleware options?
With the changes for #42 the response selection stores the mimetype too. 

Solution with middleware:
```
middleware: {
	'/rest/products/#{productCode}/GET'(serverOptions, requestOptions) {
		switch (requestOptions.req.headers.accept) {
			case 'text/html': return 'success.html';
			default: return 'success.json';
		}
	}
},
```
