### ISSUE TITLE
Question: How to use other Raml files in the mock server

### ISSUE THREAD

**Issue by primeminister** [smollweide/node-mock-server#53]
I have several raml files from other project but want to integrate that into one mock server.
Can I put them somewhere and run a command so it can be used by node-mock-server

**Comment by smollweide** [comment]
Hi @primeminister,
raml is not supported yet but it's an good idea.
As a workaround you can use [ramldt2jsonschema](https://github.com/raml-org/ramldt2jsonschema) to convert raml to jsonschema. With the jsonschema you are able to create an json response that looks like a swagger response and import that by using the swagger-import.
