### ISSUE TITLE
Not able to change status code for error response

### ISSUE THREAD

**Issue by AXV1140** [smollweide/node-mock-server#54]
How to simulate response with status other than 200. 
```
**Below is the success.json file.**
<%

var data = {};

var init = params.id;

    switch (init) {
        case '1':
        data = response[init];
        console.log("I am "+ init);
        break;
        case '2':
        data = response['error'];
        console.log("I am "+ init);
        break;  
        default:
        data= response['error-401'];
            break;
    }
%>

<%-JSON.stringify(data);%>
```
In all the case the response is going with 200 as status code. But for error response , am expecting status code as 400.
Please help with some code snippet through which we can change status code based on scenarios.

**Comment by kumar88kanishk** [comment]
@smollweide please can you guide us here, we are stuck with this current scenario

**Comment by smollweide** [comment]
Hi @kumar88kanishk,
good point. Sounds like an case for the middleware:
[readme middleware](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-middleware.md). But I will take care on your solution later on.

Greetings

**Comment by smollweide** [comment]
The middleware is the only way to solve this.
