### ISSUE TITLE
Navigates to root after adding new resource

### ISSUE THREAD

**Issue by dschulten** [smollweide/node-mock-server#56]
I have created a custom URL path for the ui using uiPath: '/ui'. I use node-mock-server to serve my app resources at /.

After adding a new resource through the +Add button the application navigates to /, i.e. instead of the newly added resource I see my application. 

The UI should navigate back to /ui instead.

**Comment by smollweide** [comment]
Hi @dschulten,
thank you for the report.
It's fixed with v0.17.3
