### ISSUE TITLE
Express is not a function

### ISSUE THREAD

**Issue by JonWallsten** [smollweide/node-mock-server#6]
I'm getting the following error when trying to run
```
node app.js
```

```
Type error: express is not a function
```

Am I doing something wrong?

**Comment by smollweide** [comment]
@JonWallsten
In the package file express is added as dependency (version > 0.6.4): [package.json](https://github.com/smollweide/node-mock-server/blob/master/package.json#L33) 
I published the current version 0.7.1, which also includes this fix.

If node is older than 0.12 please install newer version.
If node-mock-server is older than 0.7.0 run `npm install node-mock-server@0.7.1`

or run `npm install express`

**Comment by JonWallsten** [comment]
Thanks! I ran npm install express yesterday, checked the package file and found it missing. I installed through npm though, maybe 0.7.1 is not published? I'll force update today.
