### ISSUE TITLE
Make automatic open an option

### ISSUE THREAD

**Issue by dschulten** [smollweide/node-mock-server#62]
Currently opening can only be suppressed by running the mock server with NODE_ENV = 'test'. Please make that an official option (sth. like options: {open: true}) so that the behaviour can be controlled via configuration or when calling mockServer().

The use case is: once the node-mock-server has opened a ui, it should be possible to run it multiple times without ending up with numerous ui tabs. Opening by default is fine.

**Comment by smollweide** [comment]
That is already implemented in feature/tunnel. Available with `npm install node-mock-server@alpha-1`
