### ISSUE TITLE
How to configure 500er response?

### ISSUE THREAD

**Issue by faruk** [smollweide/node-mock-server#64]
Hi smollweide,

I am struggling with the configuration of node-mock-server. I want to mock various HTTP responses (500, 409, 404, 400, 201, 200 etc). Unfortunately I can't understand the documentation on that part. I understand, that you can create files like `error.<code>.json`. But how do i invoke the node-mock-server to respond with the responses **other** than 400, 200 and the contents of the success.json but the content of the specific` error.<code>.json`?

**Comment by smollweide** [comment]
Hi @faruk,
you are right the statusCode can be controlled by the response file name eg. error-401.json `error-<code>.json`.
If you need a maximum of flexibility you should use the middleware.

Example:
´´´
'/rest/products/#{productCode}/GET'(serverOptions, requestOptions) {
	var productCode = requestOptions.req.params[0].split('/')[3];

	if (productCode === '1234') {
		requestOptions.res.statusCode = 201;
		requestOptions.res.end('product 1234');
		return null;
	}

	return 'success';
}
´´´
