### ISSUE TITLE
OPTIONS request gives me a 500 (obviously)

### ISSUE THREAD

**Issue by sebastiandeutsch** [smollweide/node-mock-server#68]
Hi,

the frontend I'm using is doing an OPTIONS request due to checking the CORS headers. Will I need to add OPTIONS as a mocked http verb for every other verb to avoid a 500 (due to file not found) or do I miss something in the configuration.

Thanks

**Comment by smollweide** [comment]
Hi @sebastiandeutsch,
you need to add an OPTIONS mock response in the same as you did for all other responses.
Headers can be defined in separate file see [response header readme](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-response-header.md) for more informations.

Did this solved you problem?

**Comment by sebastiandeutsch** [comment]
Thanks for the quick response. Actually that's what I did in the first place. But it felt wrong since all the OPTIONS mocks look the same. Currently I'm solving it by adding a express middleware and checking for OPTIONS.

**Comment by smollweide** [comment]
Solution (enhancement):
- [ ] define OPTIONS fallback in config
- [ ] in case of there is no OPTIONS mock response in endpoint directory use the fallback.
- [ ] also make sure headers can be defined for the fallback response

**Comment by sebastiandeutsch** [comment]
Where would you implement this behavior? In `MockController/getResponseOptions`?

**Comment by smollweide** [comment]
Exact, this is the correct method.

**Comment by sebastiandeutsch** [comment]
Hey - was the solution I proposed as intended? Love to get some feedback.

**Comment by smollweide** [comment]
Hi @sebastiandeutsch,
sorry for the delay was in holiday and thanks for you pull-request.
I merged it and some parts see this commits:
- 98754b0
- 80aa065
- f62755a
- f6b5447

**Comment by sebastiandeutsch** [comment]
Hi @smollweide - I hope you had a great vacation, glad that this PR made it.

**Comment by smollweide** [comment]
Published. `npm i node-mock-server@0.18.2`
