### ISSUE TITLE
On windows "/rest/v1/products/" gives a wrong path

### ISSUE THREAD

**Issue by sebastiandeutsch** [smollweide/node-mock-server#71]
Hi,

I need the mock server to run on Windows. So far it works (though a lot of the directory concatenation has the wrong path separator ¯\_(ツ)_/¯).

Unfortunately I have a problem:

http://localhost:3001/rest/v1/products/ - calculates a wrong folder name
http://localhost:3001/rest/v1/products - if I remove the slash it works

Best

Sebastian

**Comment by smollweide** [comment]
Hi @sebastiandeutsch,
therefor you should change the foldername eg. with "#" in end or without.
Usually an API definition has just one variant. Removing the slashes isn't my preferred way to fix this.

**Comment by sebastiandeutsch** [comment]
I guess you're right - an API should have just one definition.

But the path generation on windows is really messed up if I add the trailing slash. The generated path tries to read a file at `C:\GET\mock/response.txt`. Wouldn't it be lovely to sanity check if the paths are leaving __dirname?
