### ISSUE TITLE
Question: Different 2xx status codes?

### ISSUE THREAD

**Issue by pablophg** [smollweide/node-mock-server#77]
I wonder if there is some way to use other status codes than 200 OK for non error responses. Like, for example, how would I send a 204. Maybe I missed this funcionality. but I could not find a way. Not even as an "error".

Edit: I found about #64 Maybe for success it could be the same as for error (example: success-204.json)

Thank you!

**Comment by smollweide** [comment]
Hi @pablophg,
yes this is a similar issue.
Here is the documentation file: [readme-expected-response](https://github.com/smollweide/node-mock-server/blob/master/doc/readme-expected-response.md)

Thank you
