### ISSUE TITLE
Response headers/cookies example/test?

### ISSUE THREAD

**Issue by leegee** [smollweide/node-mock-server#80]
I have a mock with response `login-ok.json` and added `login-ok.header.json` (sic: `header` not `headers`) that contains `{"Set-Cookie":"sessionid=asdfasdf", "Other": "asdfasdf" }`, yet I detect neither with the response.

Do you have a test or sample?  Can you see what I'm doing wrong?

**Comment by smollweide** [comment]
Hi @leegee,
yes it's documented here: https://github.com/smollweide/node-mock-server/blob/master/doc/readme-response-header.md

You can define headers globally witch will be set for every response or a specific one like you did it.

Here is an example:
https://github.com/smollweide/node-mock-server/blob/master/demo/rest/products/%23/GET/mock/success.headers.json

If you rename the file to `login-ok.headers.json` it should work.

**Comment by leegee** [comment]
Thanks. I've tried with a file name that uses `header` (as in the docs' `Add an *.header.json beside the expected response file`) and the plural you suggested, but I'm not seeing any headers in the response, which does contain the expected body.

**Comment by leegee** [comment]
It works fine, thanks --- it *was* the typo in the docs that threw me.
