### ISSUE TITLE
hello world example with some data

### ISSUE THREAD

**Issue by husayt** [smollweide/node-mock-server#94]
Currently it is very difficult to evaluate the project.  It's great to have a complex demo covering all the features. What would also be nice is to have another simple demo just serving some sample data. That will allow newcomers to start quickly and with time start using more advanced features.

**Comment by smollweide** [comment]
Hi @husayt,
you could use the init script. 

1. Install npm package:
`npm install node-mock-server --save-dev`
2. Start init process:
`node node_modules/node-mock-server/init`

This will create everything need for you, without sample data.

If this is not helpful for you, what should be part of the simple demo?
