### ISSUE TITLE
Delay in reponse body

### ISSUE THREAD

**Issue by ZappaGit** [smollweide/node-mock-server#99]
is node-mock-server able to specify any delay of the response?

Thanks in advance

**Comment by smollweide** [comment]
Hi @ZappaGit,
yes you can configure a response delay in preferences.

![kapture 2018-04-14 at 15 50 37](https://user-images.githubusercontent.com/2912007/38768974-b3bf8f64-3ffb-11e8-9812-9613aa1e20c6.gif)
